name: carro_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  device_preview: ^1.1.0
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
  - family: Anton
    fonts:
      - asset: assets/fonts/Anton-Regular.ttf
        weight: 700

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  assets:
   - assets/controle.png
   - assets/controle.jpeg

